const {test}=require('node:test');const assert=require('node:assert/strict');
const {Wallet,Transaction,keccak256,verifyMessage}=require('ethers');
const {EvmService,NETWORKS,hex,quantity,personalMessage}=require('../desktop/evm.cjs');
function harness(){const wallet=Wallet.createRandom(),calls=[];let chain=NETWORKS[0].chainId;
 const service=new EvmService(async(_url,{body})=>{const {method,params}=JSON.parse(body);calls.push({method,params});const result={eth_chainId:hex(chain),eth_getTransactionCount:'0x0',eth_gasPrice:'0x3b9aca00',eth_estimateGas:'0x5208',eth_getBalance:'0xde0b6b3a7640000'}[method]??(method==='eth_sendRawTransaction'?keccak256(params[0]):null);return Response.json({jsonrpc:'2.0',id:1,result});});
 service.network=NETWORKS.find(n=>n.id==='igra-testnet');return {wallet,calls,service,setChain:n=>chain=n};}
test('EVM signing preserves reviewed recipient, amount, chain and fee',async()=>{const {wallet,calls,service}=harness(),to=Wallet.createRandom().address;const input={from:wallet.address,to,value:'0x7b'};const prepared=await service.prepare(input,wallet.address);input.to=Wallet.createRandom().address;const hash=await service.broadcast(prepared,wallet);const raw=calls.find(c=>c.method==='eth_sendRawTransaction').params[0];const tx=Transaction.from(raw);assert.equal(tx.to,to);assert.equal(tx.value,123n);assert.equal(tx.chainId,38836n);assert.equal(tx.from,wallet.address);assert.equal(tx.hash,hash);assert.equal(tx.gasLimit,25200n);});
test('reject mismatched node, account, chain and unknown fields',async()=>{const {wallet,service,setChain}=harness();const input={from:wallet.address,to:wallet.address};await assert.rejects(service.prepare({...input,from:Wallet.createRandom().address},wallet.address),/account mismatch/);await assert.rejects(service.prepare({...input,chainId:'0x1'},wallet.address),/chain mismatch/);await assert.rejects(service.prepare({...input,authorizationList:[]},wallet.address),/Unsupported/);setChain(1);await assert.rejects(service.prepare(input,wallet.address),/wrong chain/);});
test('lock/revoke or chain switch after review prevents broadcasting',async()=>{const {wallet,service,calls}=harness();const prepared=await service.prepare({from:wallet.address,to:wallet.address},wallet.address);await assert.rejects(service.broadcast(prepared,wallet,()=>false),/authorization changed/);service.revision++;await assert.rejects(service.broadcast(prepared,wallet),/changed/);assert.equal(calls.filter(c=>c.method==='eth_sendRawTransaction').length,0);});
test('personal_sign uses EIP191 and rejects a different account',async()=>{const wallet=Wallet.createRandom();const bytes=personalMessage(['0x68656c6c6f',wallet.address],wallet.address);assert.equal(verifyMessage(bytes,await wallet.signMessage(bytes)),wallet.address);assert.throws(()=>personalMessage(['0x00',Wallet.createRandom().address],wallet.address),/mismatch/);assert.throws(()=>quantity('-1'));assert.throws(()=>quantity('0x00'));});
test('history is written before submission; storage failure prevents sending',async()=>{
 const {wallet,service,calls}=harness();const prepared=await service.prepare({from:wallet.address,to:wallet.address},wallet.address);
 service.history={before:()=>{throw Error('Disk full');}};await assert.rejects(service.broadcast(prepared,wallet),/Disk full/);assert.equal(calls.filter(c=>c.method==='eth_sendRawTransaction').length,0);
 let saved;service.history={before:record=>{saved=record;assert.equal(calls.filter(c=>c.method==='eth_sendRawTransaction').length,0);},after:record=>{assert.equal(record.hash,saved.hash);assert.equal(calls.filter(c=>c.method==='eth_sendRawTransaction').length,1);}};
 const hash=await service.broadcast(prepared,wallet);assert.equal(saved.hash,hash);assert.equal(saved.network,'igra-testnet');assert.ok(!Object.hasOwn(saved,'signed'));
});
