const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const w=require('@kluster/kaspa-wasm');const {Vault}=require('../desktop/vault.cjs');const {prepareKrc20,signKrc20,transferData}=require('../desktop/krc20.cjs');
const {Krc20Operations}=require('../desktop/operations.cjs');
test('KRC20 commit/reveal binds operation, exact outpoint, and refunds to owner',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'nexus-krc-'));let script;
 try{const vault=new Vault(path.join(directory,'vault.json'));await vault.create(crypto.randomBytes(24).toString('hex'));const {address,publicKey}=vault.kaspaIdentity();script=w.payToAddressScript(address);const entries=[{address,outpoint:{transactionId:crypto.randomBytes(32).toString('hex'),index:0},amount:500000000n,scriptPublicKey:script,blockDaaScore:1n,isCoinbase:false}];
 const prepared=await prepareKrc20({network:'testnet-10',address,publicKey,entries,transfer:{tick:'TEST',recipient:address,amount:'1.00000001',decimals:8}});assert.equal(prepared.data.amt,'100000001');const signed=signKrc20(prepared,vault);const commit=JSON.parse(signed.commit),reveal=JSON.parse(signed.reveal);assert.equal(commit.id,prepared.commitId);assert.equal(reveal.inputs[0].transactionId,commit.id);assert.equal(reveal.inputs[0].index,prepared.commitIndex);assert.ok(reveal.inputs[0].signatureScript.endsWith(prepared.redeemScript));assert.ok(reveal.outputs.every(o=>o.scriptPublicKey==='0000'+script.script));assert.ok(Buffer.from(prepared.redeemScript,'hex').includes(Buffer.from(JSON.stringify(prepared.data))));assert.throws(()=>transferData({tick:'TEST',recipient:address,amount:'0.000000001',decimals:8},'testnet-10'));
 let visible=[];const submissions=[];const rpc={getUtxosByAddresses:async()=>({entries:visible}),submitTransaction:async({transaction})=>{submissions.push(transaction.id);return {transactionId:transaction.id};}};const service={network:'testnet-10',withRpc:fn=>fn(rpc)};
 const store=new Krc20Operations(path.join(directory,'operations'),service),record=await store.create(prepared,signed);
 await assert.rejects(store.run(record.id,()=>true),/Waiting for commitment/);assert.equal((await store.get(record.id)).state,'committed');
 visible=[{outpoint:{transactionId:signed.commitId,index:prepared.commitIndex},amount:BigInt(prepared.deposit)}];
 const restarted=new Krc20Operations(path.join(directory,'operations'),service);await restarted.run(record.id,()=>true);assert.equal((await restarted.get(record.id)).state,'reveal-broadcast');assert.deepEqual(submissions,[signed.commitId,signed.revealId]);
 visible=[{outpoint:{transactionId:signed.revealId,index:0}}];await restarted.run(record.id,()=>true);assert.equal((await restarted.get(record.id)).state,'revealed');assert.equal(submissions.length,2);
 }finally{script?.free();await fs.rm(directory,{recursive:true,force:true});}
});
